### ISSUE TITLE
Fix File permissions on tasks

### ISSUE THREAD

**Issue by sean-m-sullivan** [redhat-cop/tower_utilities#12]
roles/install_ocp/tasks/install_ocp.yml:29: [E208] File permissions not mentioned
roles/install_ocp/tasks/install_ocp.yml:45: [E208] File permissions not mentioned
roles/pre_tasks/tasks/pre_tasks.yml:14: [E208] File permissions not mentioned
roles/pre_tasks/tasks/pre_tasks.yml:28: [E208] File permissions not mentioned
roles/tower_cert/tasks/main.yml:2: [E208] File permissions not mentioned
roles/tower_cert/tasks/main.yml:10: [E208] File permissions not mentioned

This needs to be explored and tested, E208 has been disabled in a recent PR.

**Comment by Tompage1994** [comment]
E208 has now been re-enabled and the linting all seems file
