### ISSUE TITLE
README for aap_ocp_install role suggest to use wrong variable name

### ISSUE THREAD

**Issue by ansiblejunky** [redhat-cop/tower_utilities#159]
# Summary

The README for the `aap_ocp_install` role suggests to use `aap_ocp_install_connection`, but code uses `aap_ocp_install_ocp_connection` that references `ocp` twice in the variable name.  I recommend fixing the code to match the more sensible variable name.

# Issue Type

- Bug Report

# Ansible, Collection, Docker/Podman details

```console (paste below)
ansible --version

ansible-galaxy collection list

podman --version

```

- ansible installation method: one of source, pip, OS package, EE

# OS / ENVIRONMENT

# Desired Behavior

# Actual Behavior

Please give some details of what is actually happening.
Include a [minimum complete verifiable example] with:

- playbook / task
- configuration file / list
- error

```console (error)

```

# STEPS TO REPRODUCE

```yaml (playbook/task)

```

```yaml (config/list/array/variables)

```

[minimum complete verifiable example]: http://stackoverflow.com/help/mcve

**Comment by sean-m-sullivan** [comment]
Pr is in, and release will be soon, let us know if this does not fix it.
