### ISSUE TITLE
Ability to define Instance Groups during aap_setup_install

### ISSUE THREAD

**Issue by nodje** [redhat-cop/tower_utilities#180]
I'm using 2.2.4

I can't find the ability to define an Instance Group.

Using the "traditional" inventory definition-> setup.sh pre-flight->setup.sh, it's possible to define for instance a group:
```
[isolated_node_bastion]
node1
node2
```

Right now I can only use
``` 
execution_nodes:
    - execution-1.example
    - execution-2.example
```
to add dedicated execution node.

But there doesn't seem to be a way to assign these execution_nodes to a specific Instance Group

**Comment by mondherGL** [comment]
same issue

**Comment by sean-m-sullivan** [comment]
Right now Any groups keys defined are created
https://github.com/redhat-cop/aap_utilities/blob/c1b8261c00af30645c333c34648a8e84f817c1c3/roles/aap_setup_prepare/templates/inventory.j2#L3C21-L3C45

[This is a generated INI file](https://github.com/PacktPublishing/Demystifying-Ansible-Automation-Platform/blob/main/ch14/global_mesh)
[This is one using vars](https://github.com/PacktPublishing/Demystifying-Ansible-Automation-Platform/blob/main/ch14/global_mesh_var.yml)
And this the instance diagram to accompany the above two files
![image](https://github.com/redhat-cop/aap_utilities/assets/30054029/d352b78c-2c05-4c85-adfa-0c7d0169ffb8)


[As per the Installer Mesh Documentation](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.4/html/red_hat_ansible_automation_platform_automation_mesh_guide/design-patterns)
 If the name of a group of nodes begins with instance_group_, the installer recognises it as an instance group and adds it to the Ansible Automation Platform user interface.

**Comment by nodje** [comment]
thanks a bunch @sean-m-sullivan 
An example is all we needed. I guess aap_setup_prepare/README.md is short of this use case and somehow we didn't figure it out.
I wasn't aware of the book, congrats!
Will try to get a copy.

**Comment by sean-m-sullivan** [comment]
yes, we need to updated the readme on this, Going to reopen this issue as this is the case, and sorry it took me a bit to come back to it. This is a case where we thought it was in the readme, but it definitely is not.
