### ISSUE TITLE
tower_database[...whatever...] is documented almost everywhere, but only used in pre_tasks

### ISSUE THREAD

**Issue by ericzolf** [redhat-cop/tower_utilities#32]
The following command shows that `tower_database[...whatever...]` is documented almost everywhere, but only used in "pre_tasks":

```
tower_cert/README.md
backup/README.md
install/README.md
pre_tasks/defaults/main.yml
pre_tasks/tasks/main.yml
pre_tasks/templates/inventory.j2
pre_tasks/README.md
restore/README.md
```

I strongly suspect a wild cut&paste effect. We should do the same exercise of cleaning up README.md resp. `defaults/main.yml` as I did for the tower_configuration.

_Originally posted by @ericzolf in https://github.com/redhat-cop/tower_utilities/pull/30#discussion_r566645071_

**Comment by sean-m-sullivan** [comment]
I think the most practicle solution is a mixture of what Tom suggested, 

1. We have variables used in pre-tasks that are used for various methods, AH install, OCP install, Tower install, That users may not know to go to find them in pretasks. 

I think the most practicle solution would be to created a Readme that describes these variables that are "shared" and link to it in Pretasks/install/backup/restore roles.

**Comment by Tompage1994** [comment]
This has been fixed by the restructure of the repo
