### ISSUE TITLE
pre-tasks inventory.js Automation Hub variables

### ISSUE THREAD

**Issue by crenwick93** [redhat-cop/tower_utilities#37]
I think this may be a typo?

automationhub_pg_database='{{ tower_ah_pg_database }}'
automationhub_pg_username='{{ tower_ah_pg_database }}'
automationhub_pg_password='{{ tower_ah_pg_database }}'

Surely we aren't setting all of these as tower_ah_pg_database? Should this not be:

automationhub_pg_database='{{ tower_ah_pg_database }}'
automationhub_pg_username='{{ tower_ah_pg_username  }}'
automationhub_pg_password='{{ tower_ah_pg_password }}'

**Comment by Tompage1994** [comment]
Yes. Looks like you're probably right there. Should probably be `tower_ah_pg_username` and `tower_ah_pg_password`.

PR very much welcome

**Comment by sean-m-sullivan** [comment]
Looks like this was fixed in #38, closing.
