### ISSUE TITLE
Tower OpenShift Install

### ISSUE THREAD

**Issue by Tompage1994** [redhat-cop/tower_utilities#6]
We want to be able to install Tower on OpenShift in the same way we can install Tower normally. 

A `tower_install_ocp` (or similar) role should be created which follows the same pattern of `tower_install`

**Comment by ericzolf** [comment]
A looooong time ago, I did something like this, but never pushed it to the end, perhaps it helps someone to start with:
https://github.com/redhat-cop/automate-tower/pull/9
