### ISSUE TITLE
Tower references

### ISSUE THREAD

**Issue by branic** [redhat-cop/tower_utilities#73]
I'm thinking the references to Tower in the README and some of the roles should be changed to Controller and/or Ansible Automation Platform.

Before opening a PR with changes I'd like to gather feedback on if the references should be changed. Thoughts?

**Comment by sean-m-sullivan** [comment]
It should be following the following conventions
Red Hat Ansible Automation Platform
Automation hub
Automation controller
Automation services catalog
Automation mesh  
Automation execution environments 
So say the Ansible Product Marketing Component and feature naming usage guidance

**Comment by branic** [comment]
I'll start working on some PR's.

**Comment by djdanielsson** [comment]
closing, hopefully most of this has been updated and anything left can just get PR'ed
