### ISSUE TITLE
Change the Instance checkers to use the inventory variables

### ISSUE THREAD

**Issue by sean-m-sullivan** [redhat-cop/tower_utilities#78]
https://github.com/redhat-cop/aap_utilities/blob/13f7f661c35cbc66c1b47f4f5c565381cd130332/roles/aap_setup_install/tasks/main.yml#L4-L32

For the status checks we should use the inventory variables
automationhub_admin_password
admin_password

**Comment by sean-m-sullivan** [comment]
I accidentally bricked my install, and fixed this in the process.

**Comment by djdanielsson** [comment]
so this is fixed? @sean-m-sullivan
