### ISSUE TITLE
Move away setup.log before restarting an installation

### ISSUE THREAD

**Issue by ericzolf** [redhat-cop/tower_utilities#80]
I realized that setup.log isn't overwritten by setup.sh if it already exists, so that the log gets lost in such cases (at least if running setup.sh as non-root). There should hence be the possibility to move away a potentially existing setup.log. It's not as easy as it sounds because Ansible doesn't have a good option to _move_ things (I don't think we want to simply _remove_ the log file).

**Comment by djdanielsson** [comment]
I mean move is just copy and then delete so it should be pretty easy

**Comment by ericzolf** [comment]
Related to https://issues.redhat.com/browse/AAP-4555 - so it should be implemented as a fix we can easily remove once fixed in the product.
@djdanielsson but you should remove only if the copy was successful, nothing one can't overcome, agreed.
