### ISSUE TITLE
Double check minimum ansible version.

### ISSUE THREAD

**Issue by sean-m-sullivan** [redhat-cop/tower_utilities#83]
Test current roles versus ansible 2.9 and Tower 3.8/AAP 1.2, and see if they still work with the versions on the roles being bumped to 2.12

**Comment by djdanielsson** [comment]
do we want to support AAP 1.2 at this point? or can we close this?

**Comment by sean-m-sullivan** [comment]
I don't think we check for it, and in reality it should work, but we no longer support it.
