### ISSUE TITLE
Collection requirements

### ISSUE THREAD

**Issue by sean-m-sullivan** [redhat-cop/tower_utilities#89]
How do we want to handle requirements, In redhat_cop.controller_configuration we leave off awx.awx or ansible.controller because it lets the users use what they want. 

With the addition of the ocp installer it requires either     "redhat.openshift": ">=2.0.1", or community.okd, and galaxy complains if we set the galaxy.yml with something it can't find like redhat.openshift. 

For now I've deleted it from the galaxy.yml, until we decide differently, but I am documenting it here.

**Comment by Tompage1994** [comment]
I think do the same as we do for controller_configuration. Leave it to the user to decide and make it explicit in the readme they need one or the other

**Comment by sean-m-sullivan** [comment]
We are leaving it to the user, closing issue.
