### ISSUE TITLE
controller_hostname and ah_hostname within aap_setup_install not variabilised

### ISSUE THREAD

**Issue by alawong** [redhat-cop/tower_utilities#90]
within the aap_setup_install role, 2 default variables, controller_hostname, and ah_hostname are used to check if controller and AH are running. However, they are set to (literally):

controller_hostname: aap_setup_prep_inv_nodes['automationcontroller'][0]
ah_hostname: aap_setup_prep_inv_nodes['automationhub'][0]

As they are missing the brackets, these tasks fail.

**Comment by Tompage1994** [comment]
Good spot. I've accepted your PR (just waiting for it to run through CI)

As a workaround before this can be released, you can set extra vars for the values which are broken, namely:

```
controller_hostname: "{{ aap_setup_prep_inv_nodes['automationcontroller'][0] }}"
ah_hostname: "{{ aap_setup_prep_inv_nodes['automationhub'][0] }}"
```
