### ISSUE TITLE
Incorrect tag???

### ISSUE THREAD

**Issue by branic** [redhat-cop/tower_utilities#97]
https://github.com/redhat-cop/aap_utilities/blob/81be4b98694fb527db51ef1c94511f2131d932e7/roles/aap_remove/tasks/main.yml#L13

I think this tag should not be `controller`, it should probably be something like `hub`.

As a side-note based on a comment from @ericzolf (https://github.com/redhat-cop/aap_utilities/pull/93#issuecomment-1242717206) maybe we should instead look at removing all tags from the roles. Thoughts?

**Comment by sean-m-sullivan** [comment]
agreed on changing to hub, I think that tags are useful but at same time it should be the variable or tag, not both.
