### ISSUE TITLE
Backup role does not add much value

### ISSUE THREAD

**Issue by ansiblejunky** [redhat-cop/tower_utilities#99]
Looking at the [backup](./roles/backup/) role, it is just running the backup command (setup.sh -b). Is there something else the role can perform? otherwise I could just run the setup.sh command myself.  Also, I'm not sure why the role asks for Postgres credentials etc when all of this info should be in the `inventory` file and leveraged using `setup.sh -i inventory -b` command. 

Also, of course, need to rewrite the role to talk about AAP instead of Tower.

**Comment by djdanielsson** [comment]
what else would you want it to do? the point of this is to allow you to automate it so you don't have to run it yourself. as for the other points I would have to test it since I haven't played with it really myself
